### ISSUE TITLE
Looking forward to the open-source code

### ISSUE THREAD

**Issue by vanity1129** [yaoyao-liu/online-hyperparameter-optimization#1]
Thanks for your excellent work!

Looking forward to your open-source code！

And I would like to know roughly when the source code will be open?

**Comment by yaoyao-liu** [comment]
Hello @vanity1129,

Thank you so much for your interest in our work. As I just moved from Germany to the United States, I don't have time to organize and clean the code recently. I plan to release it in one or two months. I am truly sorry for the inconvenience. 

If you need the preliminary code, you may contact me via email (yliu538@jhu.edu). I can send it to you today. If you have any further questions, please do not hesitate to contact me.

Best regards,

Yaoyao

**Comment by vanity1129** [comment]
Thanks for your reply and I'll send you an email today for the code.
